name: Publish package to GitHub Packages
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@mag5'
      - run: echo -e "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}\n@mag5:registry=https://npm.pkg.github.com\nalways-auth=true" > ~/.npmrc
      - run: cat ~/.npmrc
      - run: echo $NPM_CONFIG_USERCONFIG
      - run: cat $NPM_CONFIG_USERCONFIG
#       - run: npm whoami
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
